[build]
  # run your custom build script
  command = "sh netlify_build.sh"
  publish = "apps/frontend/build/web"

# Single-page-app rewrite so every route falls back to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200